"""initial schema: tenants / workflows / workflow_steps / agent_decisions / tool_calls

Revision ID: 0001
Revises:
Create Date: 2026-08-24 17:58:09.343110
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('isolation_mode', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workflows',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('product_idea', sa.Text(), nullable=False),
    sa.Column('marketplaces', sa.JSON(), nullable=False),
    sa.Column('target_market', sa.String(length=64), nullable=False),
    sa.Column('risk_preference', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_node', sa.String(length=64), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_index('ix_workflows_tenant_status', 'workflows', ['tenant_id', 'status'], unique=False)
    op.create_table('agent_decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=32), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('decision_type', sa.String(length=64), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('chosen_option', sa.String(length=64), nullable=False),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decisions_tenant_id'), 'agent_decisions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_workflow_id'), 'agent_decisions', ['workflow_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=32), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('input_summary', sa.JSON(), nullable=True),
    sa.Column('output_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_tenant_id'), 'tool_calls', ['tenant_id'], unique=False)
    op.create_index('ix_tool_calls_tenant_idem', 'tool_calls', ['tenant_id', 'idempotency_key'], unique=False)
    op.create_index(op.f('ix_tool_calls_workflow_id'), 'tool_calls', ['workflow_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_steps_wf', 'workflow_steps', ['workflow_id', 'seq'], unique=False)
    op.create_index(op.f('ix_workflow_steps_tenant_id'), 'workflow_steps', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_steps_tenant_id'), table_name='workflow_steps')
    op.drop_index('ix_steps_wf', table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_tool_calls_workflow_id'), table_name='tool_calls')
    op.drop_index('ix_tool_calls_tenant_idem', table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_tenant_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_agent_decisions_workflow_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_tenant_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_index('ix_workflows_tenant_status', table_name='workflows')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_table('tenants')
    # ### end Alembic commands ###
